@startuml
participant 学员
学员 -> 课程支付页面 : 1.支付课程
activate 课程支付页面
课程支付页面 -> 添加订单 : 2.请求创建订单
activate 添加订单
添加订单 -> 设置订单 : 3.设置订单信息
activate 设置订单
设置订单 -> 用户信息表 : 4.查询用户信息
activate 用户信息表
用户信息表 --> 设置订单 : 5.返回用户信息
deactivate 用户信息表
设置订单 --> 设置订单: 6.设置成功
添加订单 -> 订单信息表 : 7.请求生成订单
deactivate 设置订单
deactivate 添加订单
activate 订单信息表
订单信息表 -> 订单信息表 : 8.生成成功
订单信息表 --> 课程支付页面 : 9.返回创建成功信息
deactivate 订单信息表
@enduml
