@startuml
participant 讲师
讲师 -> 试卷管理页面 : 1.导入试卷文件
activate 试卷管理页面
试卷管理页面 -> 添加试卷 : 2.请求导入试卷
activate 添加试卷
添加试卷 -> 保存文件 : 3.保存试卷文件
activate 保存文件
保存文件 -> 读取试卷 : 4.识别试卷信息
activate 读取试卷
读取试卷 --> 添加试卷 : 5.返回试卷信息
添加试卷 -> 添加试卷 : 6.添加试卷
添加试卷 -> 添加试卷 : 7.添加当前题目信息
添加试卷 -> 试卷信息表 : 8.保存试卷信息
deactivate 添加试卷
activate 试卷信息表
试卷信息表 -> 试卷信息表 : 9.导入成功
试卷信息表 --> 试卷管理页面: 10.显示导入试卷信息
deactivate 试卷信息表
@enduml
