@startuml
participant 学员
学员 -> 考试页面 : 1.选择试卷进行考试
activate 考试页面
考试页面 -> 设置试卷 : 2.请求试卷数据
activate 设置试卷
activate 保存考试信息
设置试卷 -> 题目信息表 : 3.请求查询题目数据
activate 题目信息表
题目信息表 --> 设置试卷 : 4.返回题目信息
deactivate 题目信息表
设置试卷 --> 考试页面: 5.返回试卷信息
deactivate 设置试卷
考试页面 -> 保存考试信息 : 6.提交试卷
保存考试信息 -> 答题信息表 : 7.保存考试信息
deactivate  保存考试信息
activate 答题信息表
答题信息表 -> 答题信息表 : 8.保存成功
deactivate 保存考试信息
答题信息表 --> 考试页面 : 9.返回考试情况
deactivate 答题信息表
@enduml
