@startuml
participant 学员
学员 -> 咨询留言页面 : 1.点击咨询
activate 咨询留言页面
咨询留言页面 -> 查找用户 : 2.请求与对方建立连接
activate 查找用户
查找用户 -> 设置聊天记录 : 3.根据用户查找聊天记录
activate 设置聊天记录
设置聊天记录 -> 添加连接 : 4.建立连接
activate 添加连接
设置聊天记录 --> 查找用户 : 5.返回聊天记录信息
deactivate 设置聊天记录
添加连接 --> 咨询留言页面 : 6.返回连接信息
deactivate 添加连接
deactivate 查找用户
学员 -> 咨询留言页面 : 7.发送聊天信息
咨询留言页面 -> 添加聊天记录 : 8.请求插入聊天信息
activate 添加聊天记录
添加聊天记录 -> 聊天记录信息表 : 9.保存聊天记录
deactivate 添加聊天记录
activate 聊天记录信息表
聊天记录信息表 -> 聊天记录信息表 : 10.保存成功
聊天记录信息表 --> 咨询留言页面 : 11.返回新增聊天记录信息
deactivate 聊天记录信息表
@enduml
